version: "3"

services:
  server:

    image: gmihtt/multi-layer:latest

    network_mode: host

    command: stack exec multi-layer-exe

    ports:
      - 8080:8080

  mongo:

    image: mongo:latest

    depends_on:
      - server
    
    ports:
      - 27017:27017

  redis:

    image: redis:latest

    ports:
      - 6379:6379
 
    depends_on:
      - server